version: '3.8'

services:
  frontend:
    build: frontend
    container_name: frontend
  backend:
    build: backend
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
    container_name: redis
    restart: "unless-stopped"
  postgres:
    image: postgres
    container_name: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx
    container_name: nginx
    restart: "unless-stopped"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend

volumes:
  database:
