version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - 5000:5000
    container_name: frontend
  backend:
    build: backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
    container_name: redis
    restart: "unless-stopped"
  postgres:
    image: postgres
    container_name: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
